import Head from "next/head";
import React from "react";

export const metadata = {
  title: "about us - you may know about us  ",
  description: "Generated by f24-1",
};

const AboutPage = () => {
  return (
    <div>
      <Head>
        <title>About Us - GlobalNews</title>
        <meta
          name="description"
          content="Learn more about GlobalNews, our mission, our values, and the team behind the headlines."
        />
      </Head>

      <main className="bg-white text-gray-900">
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">
              About GlobalNews
            </h1>
            <p className="mt-4 text-lg leading-7 text-gray-600">
              Independent journalism. Trusted by millions. Powered by people.
            </p>
          </div>

          <div className="grid gap-10 lg:grid-cols-2">
            <div>
              <h2 className="text-2xl font-semibold mb-4">Our Mission</h2>
              <p className="text-gray-700 leading-relaxed">
                At GlobalNews, our mission is to bring unbiased, accurate, and
                timely news from around the world. We are committed to the
                highest standards of journalism and transparency.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold mb-4">Our Vision</h2>
              <p className="text-gray-700 leading-relaxed">
                We believe in a world where access to information is a
                fundamental right. Our vision is to empower people with the
                knowledge they need to make informed decisions.
              </p>
            </div>
          </div>

          <div className="mt-16">
            <h2 className="text-2xl font-semibold mb-4 text-center">
              Meet the Team
            </h2>
            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4 mt-8">
              {[
                { name: "Ava Carter", role: "Editor-in-Chief" },
                {
                  name: "Liam Jackson",
                  role: "Senior Political Correspondent",
                },
                { name: "Mia Kim", role: "Foreign Affairs Reporter" },
                { name: "Noah Smith", role: "Digital Strategy Lead" },
              ].map((member) => (
                <div key={member.name} className="text-center">
                  <div className="h-24 w-24 mx-auto rounded-full bg-gray-300 mb-4" />
                  <h3 className="text-lg font-medium">{member.name}</h3>
                  <p className="text-gray-500 text-sm">{member.role}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default AboutPage;
