import Navbar from "@/components/Shared/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Shared/Footer/Footer";


export const metadata = {
  title: "news website",
  description: "Generated by f24-1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar></Navbar>
        <div className="min-h-[50vh]">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
